// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SMAControlApp.Data;

#nullable disable

namespace SMAControlApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260330093719_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("SMAControlApp.Models.ActuatorChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CurrentDisplacement")
                        .HasColumnType("REAL");

                    b.Property<double>("DesiredDisplacement")
                        .HasColumnType("REAL");

                    b.Property<double>("InputVoltage")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RequiredVoltage")
                        .HasColumnType("REAL");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("SMAControlApp.Models.Configuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActuatorCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmplifierGain")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EquationCoefficients")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("MaxVoltage")
                        .HasColumnType("REAL");

                    b.Property<double>("MinVoltage")
                        .HasColumnType("REAL");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Configs");
                });

            modelBuilder.Entity("SMAControlApp.Models.SensorSelector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SensorSelectors");
                });

            modelBuilder.Entity("SMAControlApp.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SMAControlApp.Models.ActuatorChannel", b =>
                {
                    b.HasOne("SMAControlApp.Models.User", "User")
                        .WithMany("Actuators")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SMAControlApp.Models.Configuration", b =>
                {
                    b.HasOne("SMAControlApp.Models.User", "User")
                        .WithOne("Config")
                        .HasForeignKey("SMAControlApp.Models.Configuration", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SMAControlApp.Models.SensorSelector", b =>
                {
                    b.HasOne("SMAControlApp.Models.User", "User")
                        .WithMany("SensorSelectors")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SMAControlApp.Models.User", b =>
                {
                    b.Navigation("Actuators");

                    b.Navigation("Config")
                        .IsRequired();

                    b.Navigation("SensorSelectors");
                });
#pragma warning restore 612, 618
        }
    }
}
